### ISSUE TITLE
also...

### ISSUE THREAD

**Issue by kingcrab016** [ZiLko/xdBot#68]
add click sounds as well

**Comment by Scrurr** [comment]
There is a mod for that, its called something like "clicksounds"

**Comment by HumaanK** [comment]
already a mod for that on geode called "Click Sounds"

**Comment by MultipleGaming** [comment]
but it's not realistic. Most of the sounds are stolen, even from things you wouldn't think of!
(The pop sound which is the default click sound is stolen from an OSU! Skin. the pop sound is also very popular to have in OSU! skin packs)

**Comment by Scrurr** [comment]
As I remember, other games like funky Friday or fnb, (Roblox) have a "hit
sound" feature, there are stolen sounds from osu and other things, I don't
really know if there's more games with a hit sound feature (btw funky
Friday doesn't get the sounds for itself, you have to go on to Roblox
decals to get the sounds, I guess they aren't responsable for anything)
otherwise blame the creators for stolen assets.

Em qui., 25 de abr. de 2024 13:18, Multi ***@***.***>
escreveu:

**Comment by eiscoollol** [comment]
use zcb live

**Comment by Ant2718281828459045235360** [comment]
That... isn't an issue.

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.2
